"""empty message

Revision ID: 441e6c33a64d
Revises: 
Create Date: 2021-09-16 16:31:13.236100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441e6c33a64d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgnization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('tower_id', sa.Integer(), nullable=True),
    sa.Column('tower_type', sa.String(length=30), nullable=True),
    sa.Column('ton', sa.Integer(), nullable=True),
    sa.Column('insulator_type', sa.String(length=255), nullable=True),
    sa.Column('str_num', sa.Integer(), nullable=True),
    sa.Column('str_type', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('insu_date', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=30), nullable=True),
    sa.Column('equip_status', sa.String(length=10), nullable=True),
    sa.Column('scrap_status', sa.Integer(), nullable=True),
    sa.Column('feature1', sa.String(length=30), nullable=True),
    sa.Column('feature2', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgnization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgnization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('account')
    op.drop_table('orgnization')
    op.drop_table('line')
    # ### end Alembic commands ###
